name: For me test

on:
  workflow_dispatch:

jobs:
  build:
    name: Building...
    runs-on: windows-latest
    steps:
      - name: Установка питона и т.д.
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/88avlg4iop53zp9i5sydm/Downloads.bat?rlkey=yvn2v08sxepcgfb47cpcsscpl&st=pcxql30h&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Установка зависимостей
        run: pip install requests

      - name: Создание главной папки
        run: mkdir C:\fomchik

      - name: Скачивание програмы
        run: powershell -Command "Invoke-WebRequest -Uri 'https://www.dropbox.com/scl/fi/6as2jqqwoqvy98o6296u0/finals.py?rlkey=tum8hkcnk755dbft1t9vpz0at&st=rec1lbqi&dl=1' -OutFile 'C:\fomchik\prog.py'"

      - name: IP
        run: |
          netstat -an | find "LISTEN"
          ipconfig

      - name: Включение экрана
        run: cmd /c show.bat

      - name: 6 house 1-bqwe
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/lclvcywso1brg4q0y9csw/tms.py?rlkey=fod3tesqj5q2jd078qc6ojf6q&st=hql4ulg5&dl=1" -OutFile "Dow.py"
          python Dow.py
        continue-on-error: true

      - name: yyg
        run: python time.py